classdef CloseHolesInRegion < images.automation.volume.Algorithm
    %Medical Image Processing Class
    %
    % Properties:
    %
    % SelectedLabel     Character vector that indicates the selected label
    %                   within the app. This property is immutable.
    %
    % ExecutionMode     Execution mode of the algorithm, specified as 
    %                   either 'slice' or 'volume'. When specified as 
    %                   'slice', the algorithm will be executed on one 2D 
    %                   slice at a time. When specified as 'volume', the 
    %                   algorithm will be executed on the entire volume at 
    %                   one time. 
    %
    % UseScaledVolume   Logical scalar value indicating if the volume data 
    %                   passed to the algorithm should be scaled. If true, 
    %                   the volume passed to the algorithm has been 
    %                   rescaled to span the full dynamic range and cast to 
    %                   uint8. When false, the volume passed to the 
    %                   algorithm is not modified. The default value is
    %                   false.
    %
    % Name              Name of the algorithm displayed in the algorithm 
    %                   gallery of the Medical Image Labeler app, specified as a 
    %                   string or character vector. Use '\n' as line breaks 
    %                   between words to best fit the algorithm name into 
    %                   the gallery.
    %
    % Description       Description of the algorithm displayed in the  
    %                   algorithm gallery of the Medical Image Labeler app,
    %                   specified as a string or character vector.
    %
    % Icon              Icon of the algorithm displayed in the algorithm 
    %                   gallery of the Medical Image Labeler App, specified as a 
    %                   [16x16x3] or [24x24x3] numeric matrix. If the 
    %                   specified icon is invalid, a default icon will be 
    %                   used in the gallery.
    %
    %
    % Methods:
    %
    % run             Run automation algorithm on volume data.
    %                 LABELS = run(OBJ,V,LABELS) performs the custom 
    %                 algorithm specified by OBJ when the user selects and 
    %                 runs the algorithm from the Medical Image Labeler gallery. 
    %                 LABELS is the categorical volume representing the 
    %                 current labels in the app for volume V. V is an RGB 
    %                 or grayscale volume and LABELS is a categorical array 
    %                 where the first three dimensions match the first 
    %                 three dimensions of the volume V. 
    %                   
    %                 If the user has already created labeled regions,
    %                 LABELS may have voxels labeled as the SelectedLabel
    %                 or as other labels identified by the categories of
    %                 LABELS.
    %
    %                 Create a custom algorithm to modify the values in 
    %                 LABELS and return LABELS as a categorical array. The  
    %                 categories in LABELS may not be modified.
    %
    % stop            Terminate algorithm execution
    %                 stop(OBJ) terminates the execution of custom 
    %                 algorithm OBJ.
    %

    %--------------------------------------------------------------------------
    % Auto-generated by the Medical Image Labeler App. 
    %
    % When used by the App, this the run method in this class will be 
    % called once to process the volume as specified by the user.
    %
    %--------------------------------------------------------------------------

    properties (Constant)
        Name = 'images:segmenter:CloseHolesInRegion'; % character vector | string
        
        Description = 'Close Holes In Region'; % character vector | string

        Icon = matlab.ui.internal.toolstrip.Icon('ClosingHolesInRegion-icon-24-px.png');

        ExecutionMode = 'volume'; % 'slice' | 'volume'

        UseScaledVolume = false; % true | false
    end
    
    methods
        %% run
        function labels = run(obj,~,labels)            
            mask = labels == obj.SelectedLabel;
            
            if ~any(mask(:))
                % No initial mask, do not perform morphological operation
                return;
            end
            
            mask = imclose(mask, strel('sphere', obj.Parameters.SphereRadius));
                        
            labels(labels == obj.SelectedLabel) = missing;
            labels(mask) = obj.SelectedLabel;           
        end
    end

    methods (Static)
        %% getSettings
        function obj = getSettings(~)
            obj = CloseHolesInRegionSettings;
        end
    end
end

