function [fitresult, gof] = FitModelForVeEstimation(time, concentration, startPoint, t0, fitModel)
% FitModelForVeEstimation(TIME,CONCENTRATION)
%  This is WIP code that has not been validated.
%
%  Data for 'CA Arrival Time Fit' fit:
%      T Input : time
%      Y Output: concentration
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-May-2017 17:02:18


%% Fit: 'Biexponential Fit'.
arguments
    time {mustBeNumeric}
    concentration {mustBeNumeric}
    startPoint {mustBeNumeric}
    t0 {mustBeNumeric}
    fitModel {mustBeTextScalar}
end
[tData, yData] = prepareCurveData( time, concentration );

% Set heaviside function's value at the origin to 1 and save the original
% value for the user's MATLAB environment so we can restore it after we're
% done
origheaviside = sympref('HeavisideAtOrigin',1);

% Set up fittype and options.
opts = fitoptions( 'Method', 'NonlinearLeastSquares', 'Robust', 'LAR' );
switch fitModel
    case 'Monoexponential'
        ft = fittype( 'heaviside(t-t0)*(a1*exp(-m1*(t-t0)))', ...
            'independent', 't', 'dependent', 'y' );
        opts.Lower = [0 0 t0];
        opts.Upper = [Inf Inf t0];
    case 'Biexponential'
        ft = fittype( 'heaviside(t-t0)*(a1*exp(-m1*(t-t0))+a2*exp(-m2*(t-t0)))', ...
            'independent', 't', 'dependent', 'y' );
        opts.Lower = [0 0 0 0 t0];
        opts.Upper = [Inf Inf Inf Inf t0];
    otherwise
        error('Unrecognized fit model');
end

opts.Display = 'Off';
opts.MaxFunEvals = 3000;
opts.MaxIter = 1500;
opts.StartPoint = startPoint;

% Fit model to data.
[fitresult, gof] = fit( tData, yData, ft, opts );

% Restore the original value for the heaviside function's value at the
% origin to whatever the user had set in their MATLAB preferences
sympref('HeavisideAtOrigin', origheaviside);

% % Plot fit with data.
% figure( 'Name', [fitModel ' Fit'] );
% h = plot( fitresult, tData, yData );
% legend( h, 'concentration vs. time', 'CA Arrival Time Fit', 'Location', 'NorthEast' );
% % Label axes
% xlabel time
% ylabel concentration
% grid on