function gTruthMed = FixPathsInGroundTruthMedFile(subjectName, oldRootPath, newRootPath)
    % FixPathsInGroundTruthMedFile  Utility function for fixing the filesystem path information embedded in a
    %                               groundTruthMed.mat file produced by MATLAB's Medical Image Labeler app when files
    %                               generated by the Medical Image Labeler app are later relocated and the embedded
    %                               paths no longer reflect where the associated files are stored
    %
    % Copyright (C) 2025   Michigan State University
    % Author:   Matt Latourette
    
    arguments
        subjectName string
        oldRootPath string = "L:\Dog DCE-MRI"
        newRootPath string = "C:\Images\Dog DCE-MRI"
    end

    oldProjectionsPath = fullfile(oldRootPath, subjectName, "temporal projections");
    oldGTruthPath = fullfile(oldProjectionsPath, strcat(subjectName, "_segmentation"));

    newProjectionsPath = fullfile(newRootPath, subjectName, "temporal projections");
    newGTruthPath = fullfile(newProjectionsPath, strcat(subjectName, "_segmentation"));
    load(fullfile(newGTruthPath, "groundTruthMed.mat"), 'gTruthMed');
    oldPathLabelData = fullfile(oldGTruthPath, "LabelData");
    newPathLabelData = fullfile(newGTruthPath, "LabelData");

    projections = ["MaxIP.nii", "MinIP.nii", "MeanIP.nii", "SDIP.nii", "MedianIP.nii", "IQRIP.nii"];
    numProjections = size(projections, 2);

    alternativePathsDataSource = strings(numProjections, 2);
    alternativePathsLabelData = strings(numProjections, 2);

    for(i=1:numProjections) %#ok<NO4LP>
        alternativePathsDataSource(i,:) = [fullfile(oldProjectionsPath, projections(i)), ...
            fullfile(newProjectionsPath, projections(i))];
        alternativePathsLabelData(i,:) = [fullfile(oldPathLabelData, projections(i)), ...
            fullfile(newPathLabelData, projections(i))];
    end

    unresolvedPaths = changeFilePaths(gTruthMed, vertcat(alternativePathsDataSource, alternativePathsLabelData));
    disp(unresolvedPaths);

    % rename the original ground truth file
    movefile(fullfile(newGTruthPath, "groundTruthMed.mat"), fullfile(newGTruthPath, "groundTruthMed.mat.old"));

    % save the ground truth file that has had its filesystem paths fixed
    save(fullfile(newGTruthPath, "groundTruthMed.mat"), "gTruthMed");
end