classdef LoadImagesDialogView < handle
    % LoadImagesDialogView      View class (MVC pattern) for the LoadImagesDialog GUI, which collects information 
    %                           about the image data set to be loaded into LiverDCE for analysis
    %
    % Copyright (C) 2025    Michigan State University
    % Author:   Matt Latourette
    
    %% Properties

    % Observable Properties (listeners receive notification of changes
    properties (SetObservable = true, AbortSet = true)
        Model
        UiControls
    end

    % Dependent properties
    properties (SetObservable = true, AbortSet = true, Dependent = true)
    end

    % Private Properties
    properties (Access = private)
    end

    % Private Computable Dependent Properties
    properties (Dependent = true, SetAccess = private)
    end

    %% Events
    events
    end

    %% Public Methods
    methods
        %% Constructors
        function this = LoadImagesDialogView(model)
            this.Model = model;

            % build the GUI
            this.InitializeGui();
            this.TriggerUiControlInitialization();
            this.RegisterEventListeners();
        end

        %% Getters for Computable Dependent Properties

        %% Getters and Setters
        function model = get.Model(this)
            model = this.Model;
        end

        function set.Model(this, value)
            this.Model = value;
        end

        %% Other Public Methods
    end

    %% Private Methods
    methods (Access = private)
        %% TriggerUiControlInitialization
        function TriggerUiControlInitialization(this)
            model = this.Model;
            this.OnChangedImageFileFormat(model);
            this.OnChangedSelectedAgent(model);
            this.OnChangedOtherContrastAgent(model);
            this.OnChangedUseDefaultRelaxivity(model);
            this.OnChangedLiverRelaxivity(model);
            this.OnChangedPlasmaRelaxivity(model);
            %TODO: replace the single blood relaxivity with 2 separate values for arterial and venous blood if
            %there is sufficient data in the literature to support this
            this.OnChangedBloodRelaxivity(model);
            this.OnChangedSelectedFieldStrength(model);
            this.OnChangedOtherFieldStrength(model);
            this.OnChangedFlipAngle(model);
            this.OnChangedSelectedSpecies(model);
            this.OnChangedSelectedPulseSequence(model);
            this.OnChangedAcquisitionInterval(model);
            this.OnChangedEchoTime(model);
            this.OnChangedRepetitionTime(model);
            this.OnChangedDicomFileFolderStructure(model);
            this.OnChangedFilenamePrefix(model);
            this.OnChangedUseLeadingZeros(model);
            this.OnChangedDigitPlaces(model);
            this.OnChangedFilenameExtension(model);
            this.OnChangedNumberOfSlices(model);
            this.OnChangedFilesystemPath(model);
            this.OnChangedImageSetIdentifier(model);
            this.OnChangedBrikName(model);
        end

        %% RegisterEventListeners
        function RegisterEventListeners(this)
            model = this.Model;
            addlistener(model, 'ImageFileFormat', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedImageFileFormat(this, uiEvent.AffectedObject));
            addlistener(model, 'SelectedAgent', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedSelectedAgent(this, uiEvent.AffectedObject));
            addlistener(model, 'OtherContrastAgent', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedOtherContrastAgent(this, uiEvent.AffectedObject));
            addlistener(model, 'UseDefaultRelaxivity', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedUseDefaultRelaxivity(this, uiEvent.AffectedObject));
            addlistener(model, 'LiverRelaxivity', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedLiverRelaxivity(this, uiEvent.AffectedObject));
            addlistener(model, 'PlasmaRelaxivity', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedPlasmaRelaxivity(this, uiEvent.AffectedObject));
            %TODO: replace the single blood relaxivity value with 2 separate values for arterial and venous blood
            %if there is sufficient data in the literature to support this
            addlistener(model, 'BloodRelaxivity', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedBloodRelaxivity(this, uiEvent.AffectedObject));
            addlistener(model, 'SelectedFieldStrength', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedSelectedFieldStrength(this, uiEvent.AffectedObject));
            addlistener(model, 'OtherFieldStrength', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedOtherFieldStrength(this, uiEvent.AffectedObject));
            addlistener(model, 'FlipAngle', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedFlipAngle(this, uiEvent.AffectedObject));
            addlistener(model, 'SelectedSpecies', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedSelectedSpecies(this, uiEvent.AffectedObject));
            addlistener(model, 'SelectedPulseSequence', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedSelectedPulseSequence(this, uiEvent.AffectedObject));
            addlistener(model, 'AcquisitionInterval', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedAcquisitionInterval(this, uiEvent.AffectedObject));
            addlistener(model, 'EchoTime', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedEchoTime(this, uiEvent.AffectedObject));
            addlistener(model, 'RepetitionTime', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedRepetitionTime(this, uiEvent.AffectedObject));
            addlistener(model, 'DicomFileFolderStructure', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedDicomFileFolderStructure(this, uiEvent.AffectedObject));
            addlistener(model, 'FilenamePrefix', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedFilenamePrefix(this, uiEvent.AffectedObject));
            addlistener(model, 'UseLeadingZeros', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedUseLeadingZeros(this, uiEvent.AffectedObject));
            addlistener(model, 'DigitPlaces', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedDigitPlaces(this, uiEvent.AffectedObject));
            addlistener(model, 'FilenameExtension', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedFilenameExtension(this, uiEvent.AffectedObject));
            addlistener(model, 'NumberOfSlices', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedNumberOfSlices(this, uiEvent.AffectedObject));
            addlistener(model, 'FilesystemPath', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedFilesystemPath(this, uiEvent.AffectedObject));
            addlistener(model, 'ImageSetIdentifier', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedImageSetIdentifier(this, uiEvent.AffectedObject));
            addlistener(model, 'BrikName', 'PostSet', ...
                @(uiControl,uiEvent) OnChangedBrikName(this, uiEvent.AffectedObject));
        end

        %% InitializeGui
        function InitializeGui(this)
            model = this.Model;
            hFig = figure('Visible', 'off', ...
                'Name', 'Load Images', ...
                'NumberTitle', 'off', ...
                'Position', [0 0 936 460], ...
                'Resize', 'on', ...
                'ToolBar', 'none', ...
                'MenuBar', 'none', ...
                'WindowStyle', 'normal');
            % Leaving the windowing mode at normal for now to make testing easier. May switch to modal later.
            %         'WindowStyle', 'modal');

            % Panels for grouping UI components
            hImageFileFormatButtonGroup = uibuttongroup(hFig, ...
                'Title', 'Image File Format', ...
                'Visible', 'off', ...
                'Units', 'pixels', ...
                'Position', [8 277 126 180]);
            hContrastAgentPanel = uipanel(hFig, ...
                'Title', 'Contrast Agent', ...
                'Units', 'Pixels', ...
                'Position', [140 277 314 180]);
            hMrAcquisitionParametersPanel = uipanel(hFig, ...
                'Title', 'MR Acquisition Parameters', ...
                'Units', 'Pixels', ...
                'Position', [460 277 468 180]);
            hDicomFileFolderStructureButtonGroup = uibuttongroup(hFig, ...
                'Title', 'DICOM File Folder Structure', ...
                'Visible', 'off', ...
                'Units', 'pixels', ...
                'Position', [8 194 266 80]);
            hDicomFileOptionsPanel = uipanel(hFig, ...
                'Title', 'DICOM File Options', ...
                'Units', 'Pixels', ...
                'Position', [280 194 460 80]);
            hAfniFileOptionsPanel = uipanel(hFig, ...
                'Title', 'AFNI File Options', ...
                'Units', 'Pixels', ...
                'Position', [746 194 182 80]);
                % 'Position', [746 174 182 80]);
            hImageFileOptionsPanel = uipanel(hFig, ...
                'Title', 'Image File Options', ...
                'Units', 'Pixels', ...
                'Position', [8 50 920 140]);

            % Image File Format Button Group
            hDicom = uicontrol(hImageFileFormatButtonGroup, ...
                'Style', 'radiobutton', ...
                'String', 'DICOM', ...
                'TooltipString', 'DICOM', ...
                'Position', [12 120 90 20], ...
                'Units', 'Pixels', ...
                'HandleVisibility', 'off');
            hAfni = uicontrol(hImageFileFormatButtonGroup, ...
                'Style', 'radiobutton', ...
                'String', 'AFNI', ...
                'TooltipString', 'AFNI', ...
                'Units', 'Pixels', ...
                'Position', [12 100 90 20], ...
                'HandleVisibility', 'off');
            hNifti = uicontrol(hImageFileFormatButtonGroup, ...
                'Style', 'radiobutton', ...
                'String', 'NIFTI', ...
                'TooltipString', 'NIFTI', ...
                'Position', [12 80 90 20], ...
                'HandleVisibility', 'off');
            switch(model.ImageFileFormat)
                case 'DICOM'
                    hImageFileFormatButtonGroup.SelectedObject = hDicom;
                case 'AFNI'
                    hImageFileFormatButtonGroup.SelectedObject = hAfni;
                case 'NIFTI'
                    hImageFileFormatButtonGroup.SelectedObject = hNifti;
                otherwise
                    hImageFileFormatButtonGroup.SelectedObject = hDicom;
            end
            hImageFileFormatButtonGroup.Visible = 'on';

            % Contrast Agent Panel
            hAgentNameLabel = uicontrol(hContrastAgentPanel, ...
                'Style', 'text', ...
                'String', 'Agent Name', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 146 70 13]);
            hAgentNamePopUpMenu = uicontrol(hContrastAgentPanel, ...
                'Style', 'popup', ...
                'String', model.AgentList, ...
                'TooltipString', 'Agent Name', ...
                'Value', model.SelectedAgent, ...
                'Units', 'Pixels', ...
                'Position', [12 120 100 22]);
            hOtherContrastAgentLabel = uicontrol(hContrastAgentPanel, ...
                'Style', 'text', ...
                'String', 'Other Contrast Agent', ...
                'TooltipString', 'Other Contrast Agent', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Enable', 'off', ...
                'Position', [10 96 108 13]);
            hOtherContrastAgentEditBox = uicontrol(hContrastAgentPanel, ...
                'Style', 'edit', ...
                'String', model.OtherContrastAgent, ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'Position', [10 70 107 22]);
            hUseDefaultRelaxivityCheckBox = uicontrol('Parent', hContrastAgentPanel, ...
                'Style', 'checkbox', ...
                'String', 'Use Default Relaxivity', ...
                'TooltipString', 'Use Default Relaxivity', ...
                'Value', model.UseDefaultRelaxivity, ...
                'Units', 'Pixels', ...
                'Position', [10 20 130 22]);
            hLiverRelaxivityLabel = uicontrol(hContrastAgentPanel, ...
                'Style', 'text', ...
                'String', 'Liver Relaxivity (1/s/mM)', ...
                'TooltipString', 'Liver Relaxivity (1/s/mM)', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Enable', 'off', ...
                'Position', [150 146 140 13]);
            hLiverRelaxivityEditBox = uicontrol(hContrastAgentPanel, ...
                'Style', 'edit', ...
                'String', model.LiverRelaxivity, ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'Position', [150 120 140 22]);
            hPlasmaRelaxivityLabel = uicontrol(...
                'Parent', hContrastAgentPanel, ...
                'Style', 'text', ...
                'String', 'Plasma Relaxivity (1/s/mM)', ...
                'TooltipString', 'Plasma Relaxivity (1/s/mM)', ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left', ...
                'Position', [150 96 140 13]);
            hPlasmaRelaxivityEditBox = uicontrol(...
                'Parent', hContrastAgentPanel, ...
                'Style', 'edit', ...
                'String', model.PlasmaRelaxivity, ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'Position', [150 70 140 22]);
            %TODO: replace the single blood relaxivity value with 2 separate values for arterial and venous blood
            %if there is sufficient data in the literature to support this
            hBloodRelaxivityLabel = uicontrol(...
                'Parent', hContrastAgentPanel, ...
                'Style', 'text', ...
                'String', 'Blood Relaxivity (1/s/mM)', ...
                'TooltipString', 'Blood Relaxivity (1/s/mM)', ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left', ...
                'Position', [150 46 140 13]);
            hBloodRelaxivityEditBox = uicontrol(...
                'Parent', hContrastAgentPanel, ...
                'Style', 'edit', ...
                'String', model.BloodRelaxivity, ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'Position', [150 20 140 22]);


            % MRI Acquisition Parameters Panel
            hMriFieldStrengthLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'B0 (T)', ...
                'TooltipString', 'Field Strength', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 126 46 13]);
            hMriFieldStrengthPopUpMenu = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'popup', ...
                'String', model.FieldStrengthList, ...
                'TooltipString', 'Field Strength', ...
                'Value', model.SelectedFieldStrength, ...
                'Units', 'Pixels', ...
                'Position', [12 100 78 22]);
            hOtherFieldStrengthLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Other Field Strength (T)', ...
                'TooltipString', 'Other Field Strength', ...
                'Units', 'Pixels', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left', ...
                'Position', [130 126 110 13]);
            hOtherFieldStrengthEditBox = uicontrol(...
                'Parent', hMrAcquisitionParametersPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.OtherFieldStrength), ...
                'Enable', 'off', ...
                'Units', 'Pixels', ...
                'Position', [130 100 110 22]);
            hFlipAngleLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Flip Angle (°)', ...
                'TooltipString', 'Flip Angle (°)', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [258 126 80 13]);
            hFlipAngleEditBox = uicontrol(...
                'Parent', hMrAcquisitionParametersPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.FlipAngle), ...
                'Units', 'Pixels', ...
                'Position', [258 100 80 22]);
            hSpeciesLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Species', ...
                'TooltipString', 'Species', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [356 126 52 13]);
            hSpeciesPopUpMenu = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'popup', ...
                'String', model.SpeciesList, ...
                'TooltipString', 'Species', ...
                'Value', model.SelectedSpecies, ...
                'Units', 'Pixels', ...
                'Position', [356 100 100 22]);
            hPulseSequenceLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Pulse Sequence', ...
                'TooltipString', 'Pulse Sequence', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 76 100 13]);
            hPulseSequencePopUpMenu = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'popup', ...
                'String', model.PulseSequenceList, ...
                'TooltipString', 'Pulse Sequence', ...
                'Value', model.SelectedPulseSequence, ...
                'Units', 'Pixels', ...
                'Position', [12 50 100 22]);
            hAcquisitionIntervalLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Acquisition Interval (s)', ...
                'TooltipString', 'Acquisition Interval (s)', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [130 76 110 13]);
            hAcquisitionIntervalEditBox = uicontrol(...
                'Parent', hMrAcquisitionParametersPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.AcquisitionInterval), ...
                'Units', 'Pixels', ...
                'Position', [130 50 110 22]);
            hEchoTimeLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Echo Time (ms)', ...
                'TooltipString', 'Echo Time (ms)', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [258 76 80 13]);
            hEchoTimeEditBox = uicontrol(...
                'Parent', hMrAcquisitionParametersPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.EchoTime), ...
                'Units', 'Pixels', ...
                'Position', [258 50 80 22]);
            hRepetitionTimeLabel = uicontrol(hMrAcquisitionParametersPanel, ...
                'Style', 'text', ...
                'String', 'Repetition Time (ms)', ...
                'TooltipString', 'Repetition Time (ms)', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [356 76 100 13]);
            hRepetitionTimeEditBox = uicontrol(...
                'Parent', hMrAcquisitionParametersPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.RepetitionTime), ...
                'Units', 'Pixels', ...
                'Position', [356 50 100 22]);

            % DICOM File Folder Structure Button Group
            hOrderedImages = uicontrol(hDicomFileFolderStructureButtonGroup, ...
                'Style', 'radiobutton', ...
                'String', 'Ordered Images With Numbered Filenames', ...
                'TooltipString', 'Ordered Images With Numbered Filenames', ...
                'Units', 'Pixels', ...
                'Position', [12 40 226 20]);
            hUnorderedImages = uicontrol(hDicomFileFolderStructureButtonGroup, ...
                'Style', 'radiobutton', ...
                'String', 'Unordered Images', ...
                'TooltipString', 'Unordered Images', ...
                'Units', 'Pixels', ...
                'Position', [12 20 120 20]);
            switch(model.DicomFileFolderStructure)
                case 'Ordered'
                    hDicomFileFolderStructureButtonGroup.SelectedObject = hOrderedImages;
                case 'Unordered'
                    hDicomFileFolderStructureButtonGroup.SelectedObject = hUnorderedImages;
                otherwise
                    hDicomFileFolderStructureButtonGroup.SelectedObject = hOrderedImages;
            end
            hDicomFileFolderStructureButtonGroup.Visible = 'on';

            % DICOM File Options Panel
            hFilenamePrefixLabel = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Filename Prefix', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 46 78 13]);
            hFilenamePrefixEditBox = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', model.FilenamePrefix, ...
                'Units', 'Pixels', ...
                'Position', [12 20 78 22]);
            hLeadingZerosCheckBox = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'checkbox', 'String', 'Leading Zeros', ...
                'Value', model.UseLeadingZeros, ...
                'Units', 'Pixels', ...
                'Position', [108 20 90 22]);
            hDigitPlacesLabel = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Digit Places', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [216 46 60 13]);
            hDigitPlacesEditBox = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.DigitPlaces), ...
                'Units', 'Pixels', ...
                'Position', [216 20 66 22]);
            hFilenameExtensionLabel = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Extension', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [300 46 60 13]);
            hFilenameExtensionEditBox = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', model.FilenameExtension, ...
                'Units', 'Pixels', ...
                'Position', [300 20 50 22]);
            hNumberOfSlicesLabel = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Number of Slices', ...
                'Units', 'Pixels', ...
                'Position', [368 46 84 13]);
            hNumberOfSlicesEditBox = uicontrol('Parent', hDicomFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', num2str(model.NumberOfSlices), ...
                'Units', 'Pixels', ...
                'Position', [368 20 80 22]);


            % Image File Options Panel
            hFilesystemPathLabel = uicontrol('Parent', hImageFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Filesystem Path', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 106 80 13]);
            hFilesystemPathEditBox = uicontrol('Parent', hImageFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', model.FilesystemPath, ...
                'Units', 'Pixels', ...
                'Position', [12 58 896 44], ...
                'HorizontalAlignment', 'left', ...
                'Max', 2);
            hSelectPathButton = uicontrol('Parent', hImageFileOptionsPanel, ...
                'Style', 'pushbutton', ...
                'String', 'Select Path', ...
                'Units', 'pixels', ...
                'Position', [838 30 70 22]);
            hImageSetIdentifierLabel = uicontrol(hImageFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Image Set Identifier', ...
                'TooltipString', 'Image Set Identifier', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 36 150 13]);
            hImageSetIdentifierEditBox = uicontrol(...
                'Parent', hImageFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', model.ImageSetIdentifier, ...
                'Units', 'Pixels', ...
                'Position', [12 10 150 22]);

            % AFNI File Options Panel
            hBrikNameLabel = uicontrol('Parent', hAfniFileOptionsPanel, ...
                'Style', 'text', ...
                'String', 'Brik Name', ...
                'Units', 'Pixels', ...
                'HorizontalAlignment', 'left', ...
                'Position', [12 46 70 13]);
            hBrikNameEditBox = uicontrol('Parent', hAfniFileOptionsPanel, ...
                'Style', 'edit', ...
                'String', model.BrikName, ...
                'Enable', 'off', ...
                'Units', 'Pixels', ...
                'Position', [12 20 150 22]);

            hLoadImagesButton = uicontrol('Parent', hFig, ...
                'Style', 'pushbutton', ...
                'String', 'Load Images', ...
                'Units', 'pixels', ...
                'Position', [754 20 80 22]);
            hCancelButton = uicontrol('Parent', hFig, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Units', 'pixels', ...
                'Position', [852 20 70 22]);

            this.UiControls = struct(...
                'Figure', hFig, ...
                'ImageFileFormatButtonGroup', hImageFileFormatButtonGroup, ...
                'ContrastAgentPanel', hContrastAgentPanel, ...
                'MrAcquisitionParametersPanel', hMrAcquisitionParametersPanel, ...
                'DicomFileFolderStructureButtonGroup', ...
                hDicomFileFolderStructureButtonGroup, ...
                'DicomFileOptionsPanel', hDicomFileOptionsPanel, ...
                'AfniFileOptionsPanel', hAfniFileOptionsPanel, ...
                'ImageFileOptionsPanel', hImageFileOptionsPanel, ...
                'Dicom', hDicom, ...
                'Afni', hAfni, ...
                'Nifti', hNifti, ...
                'AgentNameLabel', hAgentNameLabel, ...
                'AgentNamePopUpMenu', hAgentNamePopUpMenu, ...
                'OtherContrastAgentLabel', hOtherContrastAgentLabel, ...
                'OtherContrastAgentEditBox', hOtherContrastAgentEditBox, ...
                'UseDefaultRelaxivityCheckBox', hUseDefaultRelaxivityCheckBox, ...
                'LiverRelaxivityLabel', hLiverRelaxivityLabel, ...
                'LiverRelaxivityEditBox', hLiverRelaxivityEditBox, ...
                'PlasmaRelaxivityLabel', hPlasmaRelaxivityLabel, ...
                'PlasmaRelaxivityEditBox', hPlasmaRelaxivityEditBox, ...
                'BloodRelaxivityLabel', hBloodRelaxivityLabel, ...
                'BloodRelaxivityEditBox', hBloodRelaxivityEditBox, ...
                'MriFieldStrengthLabel', hMriFieldStrengthLabel, ...
                'MriFieldStrengthPopUpMenu', hMriFieldStrengthPopUpMenu, ...
                'OtherFieldStrengthLabel', hOtherFieldStrengthLabel, ...
                'OtherFieldStrengthEditBox', hOtherFieldStrengthEditBox, ...
                'FlipAngleLabel', hFlipAngleLabel, ...
                'FlipAngleEditBox', hFlipAngleEditBox, ...
                'SpeciesLabel', hSpeciesLabel, ...
                'SpeciesPopUpMenu', hSpeciesPopUpMenu, ...
                'PulseSequenceLabel', hPulseSequenceLabel, ...
                'PulseSequencePopUpMenu', hPulseSequencePopUpMenu, ...
                'AcquisitionIntervalLabel', hAcquisitionIntervalLabel, ...
                'AcquisitionIntervalEditBox', hAcquisitionIntervalEditBox, ...
                'EchoTimeLabel', hEchoTimeLabel, ...
                'EchoTimeEditBox', hEchoTimeEditBox, ...
                'RepetitionTimeLabel', hRepetitionTimeLabel, ...
                'RepetitionTimeEditBox', hRepetitionTimeEditBox, ...
                'OrderedImages', hOrderedImages, ...
                'UnorderedImages', hUnorderedImages, ...
                'FilenamePrefixLabel', hFilenamePrefixLabel, ...
                'FilenamePrefixEditBox', hFilenamePrefixEditBox, ...
                'LeadingZerosCheckBox', hLeadingZerosCheckBox, ...
                'DigitPlacesLabel', hDigitPlacesLabel, ...
                'DigitPlacesEditBox', hDigitPlacesEditBox, ...
                'FilenameExtensionLabel', hFilenameExtensionLabel, ...
                'FilenameExtensionEditBox', hFilenameExtensionEditBox, ...
                'NumberOfSlicesLabel', hNumberOfSlicesLabel, ...
                'NumberOfSlicesEditBox', hNumberOfSlicesEditBox, ...
                'FilesystemPathLabel', hFilesystemPathLabel, ...
                'FilesystemPathEditBox', hFilesystemPathEditBox, ...
                'SelectPathButton', hSelectPathButton, ...
                'ImageSetIdentifierLabel', hImageSetIdentifierLabel, ...
                'ImageSetIdentifierEditBox', hImageSetIdentifierEditBox, ...
                'BrikNameLabel', hBrikNameLabel, ...
                'BrikNameEditBox', hBrikNameEditBox, ...
                'LoadImagesButton', hLoadImagesButton, ...
                'CancelButton', hCancelButton);

            this.NormalizeDisplayUnits();
            this.MoveToPosition(model);
            this.MakeVisible();
        end

        %% MakeVisible
        function MakeVisible(this)
            this.UiControls.Figure.Visible = 'on';
        end

        %% MoveToPosition
        function MoveToPosition(this, uiModel)
            savedScreenPosition = uiModel.SavedScreenPosition;
            if(isempty(savedScreenPosition))
                % Move the GUI to the screen center
                movegui(this.UiControls.Figure, 'center');
            else
                movegui(this.UiControls.Figure, savedScreenPosition);
                movegui(this.UiControls.Figure, 'onscreen');
            end
        end

        %% NormalizeDisplayUnits
        function NormalizeDisplayUnits(this)
            controlsToExclude = {};
            uiControlNames = fieldnames(this.UiControls);
            numberOfUiControls = numel(uiControlNames);

            if (numberOfUiControls > 0)
                for controlIndex = 1:numberOfUiControls
                    controlName = uiControlNames{controlIndex};
                    if (~any(strcmp(controlsToExclude, controlName)))
                        uiControl = getfield(this.UiControls, controlName);
                        uiControl.Units = 'normalized';
                    end
                end
            end
        end

        %% OnChangedImageFileFormat
        function OnChangedImageFileFormat(this, uiModel)
            switch(uiModel.ImageFileFormat)
                case 'DICOM'
                    this.EnableDicomFileFolderStructurePanel();
                    this.DisableAfniFileOptionsPanel();
                    switch(uiModel.DicomFileFolderStructure)
                        case 'Ordered'
                            this.EnableDicomFileOptionsPanel();
                        case 'Unordered'
                            this.DisableDicomFileOptionsPanel();
                        otherwise
                            % default is Ordered
                            this.EnableDicomFileOptionsPanel();
                    end
                    this.DisableFlipAngleEdit();
                    this.DisableEchoTimeEdit();
                    this.DisableRepetitionTimeEdit();
                case {'AFNI', 'NIFTI'}
                    this.DisableDicomFileFolderStructurePanel();
                    this.DisableDicomFileOptionsPanel();
                    this.EnableAfniFileOptionsPanel();
                    this.EnableFlipAngleEdit();
                    this.EnableEchoTimeEdit();
                    this.EnableRepetitionTimeEdit();
                otherwise
            end
        end

        %% OnChangedSelectedAgent
        function OnChangedSelectedAgent(this, uiModel)
            selectedAgent = uiModel.SelectedAgent;
            if(~isempty(selectedAgent))
                agentName = uiModel.AgentList{selectedAgent};
                switch(agentName)
                    case {'Gd-EOB-DTPA', 'Gd-BOPTA', 'Gd-DTPA', 'Gd-BT-DO3A'}
                        this.DisableOtherContrastAgentUiControls();
                        if(uiModel.UseDefaultRelaxivity)
                            this.DisableRelaxivityControls();
                        end
                    case 'Other'
                        this.EnableOtherContrastAgentUiControls();
                    otherwise
                        this.EnableOtherContrastAgentUiControls();
                end
            else
                this.EnableOtherContrastAgentUiControls();
            end
        end

        %% OnChangedOtherContrastAgent
        function OnChangedOtherContrastAgent(~, ~)
        end

        %% OnChangedUseDefaultRelaxivity
        function OnChangedUseDefaultRelaxivity(this, uiModel)
            selectedAgent = uiModel.SelectedAgent;
            if(~isempty(selectedAgent))
                agentName = uiModel.AgentList{selectedAgent};
                if(strcmp(agentName, 'Other'))
                    this.EnableOtherContrastAgentUiControls();
                    return
                end
            end

            if(uiModel.UseDefaultRelaxivity)
                this.DisableRelaxivityControls();
            else
                this.EnableRelaxivityControls();
            end
        end

        %% OnChangedLiverRelaxivity
        function OnChangedLiverRelaxivity(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.LiverRelaxivityEditBox))
                uiControls.LiverRelaxivityEditBox.String = num2str(uiModel.LiverRelaxivity);
            end
        end

        %% OnChangedPlasmaRelaxivity
        function OnChangedPlasmaRelaxivity(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.PlasmaRelaxivityEditBox))
                uiControls.PlasmaRelaxivityEditBox.String = num2str(uiModel.PlasmaRelaxivity);
            end
        end

        %% OnChangedBloodRelaxivity
        %TODO: replace the single blood relaxivity value with 2 separate values for arterial and venous blood
        %if there is sufficient data in the literature to support this
        function OnChangedBloodRelaxivity(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.BloodRelaxivityEditBox))
                uiControls.BloodRelaxivityEditBox.String = num2str(uiModel.BloodRelaxivity);
            end
        end

        %% OnChangedSelectedFieldStrength
        function OnChangedSelectedFieldStrength(this, uiModel)
            selectedFieldStrength = uiModel.SelectedFieldStrength;
            if(~isempty(selectedFieldStrength))
                fieldStrength = uiModel.FieldStrengthList{selectedFieldStrength};
                switch(fieldStrength)
                    case 'Other'
                        this.EnableOtherFieldStrengthUiControls();
                    otherwise
                        this.DisableOtherFieldStrengthUiControls();
                end
            else
                this.EnableOtherFieldStrengthUiControls();
            end
        end

        %% OnChangedOtherFieldStrength
        function OnChangedOtherFieldStrength(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.OtherFieldStrengthEditBox))
                uiControls.OtherFieldStrengthEditBox.String = ...
                    num2str(uiModel.OtherFieldStrength);
            end
        end

        %% OnChangedFlipAngle
        function OnChangedFlipAngle(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.FlipAngleEditBox))
                uiControls.FlipAngleEditBox.String = num2str(uiModel.FlipAngle);
            end
        end

        %% OnChangedSelectedSpecies
        function OnChangedSelectedSpecies(~, ~)
        end

        %% OnChangedSelectedPulseSequence
        function OnChangedSelectedPulseSequence(~, ~)
        end

        %% OnChangedAcquisitionInterval
        function OnChangedAcquisitionInterval(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.AcquisitionIntervalEditBox))
                uiControls.AcquisitionIntervalEditBox.String = ...
                    num2str(uiModel.AcquisitionInterval);
            end
        end

        %% OnChangedEchoTime
        function OnChangedEchoTime(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.EchoTimeEditBox))
                uiControls.EchoTimeEditBox.String = num2str(uiModel.EchoTime);
            end
        end

        %% OnChangedRepetitionTime
        function OnChangedRepetitionTime(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.RepetitionTimeEditBox))
                uiControls.RepetitionTimeEditBox.String = num2str(uiModel.RepetitionTime);
            end
        end

        %% OnChangedDicomFileFolderStructure
        function OnChangedDicomFileFolderStructure(this, uiModel)
            switch(uiModel.ImageFileFormat)
                case 'DICOM'
                    switch(uiModel.DicomFileFolderStructure)
                        case 'Ordered'
                            this.EnableDicomFileOptionsPanel();
                        case 'Unordered'
                            this.DisableDicomFileOptionsPanel();
                        otherwise
                    end
                case {'AFNI', 'NIFTI'}
                    this.DisableDicomFileOptionsPanel();
                otherwise
                    this.DisableDicomFileOptionsPanel();
            end
        end

        %% OnChangedFilenamePrefix
        function OnChangedFilenamePrefix(~, ~)
        end

        %% OnChangedUseLeadingZeros
        function OnChangedUseLeadingZeros(~, ~)
        end

        %% OnChangedDigitPlaces
        function OnChangedDigitPlaces(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.DigitPlacesEditBox))
                uiControls.DigitPlacesEditBox.String = num2str(uiModel.DigitPlaces);
            end
        end

        %% OnChangedFilenameExtension
        function OnChangedFilenameExtension(~, ~)
        end

        %% OnChangedNumberOfSlices
        function OnChangedNumberOfSlices(this, uiModel)
            uiControls = this.UiControls;
            if(isvalid(uiControls.NumberOfSlicesEditBox))
                uiControls.NumberOfSlicesEditBox.String = num2str(uiModel.NumberOfSlices);
            end
        end

        %% OnChangedFilesystemPath
        function OnChangedFilesystemPath(this, uiModel)
            uiControls = this.UiControls;
            filesystemPath = uiModel.FilesystemPath;
            if(isvalid(uiControls.FilesystemPathEditBox))
                uiControls.FilesystemPathEditBox.String = filesystemPath;
            end
        end

        %% OnChangedImageSetIdentifier
        function OnChangedImageSetIdentifier(~, ~)
        end

        %% OnChangedBrikName
        function OnChangedBrikName(~, ~)
        end

        %% Uicontrol Enablers/Disablers
        function EnableDicomFileFolderStructurePanel(this)
            uiControls = this.UiControls;
            uiControls.OrderedImages.Enable = 'on';
            uiControls.UnorderedImages.Enable = 'on';
        end

        function DisableDicomFileFolderStructurePanel(this)
            uiControls = this.UiControls;
            uiControls.OrderedImages.Enable = 'off';
            uiControls.UnorderedImages.Enable = 'off';
        end

        function EnableAfniFileOptionsPanel(this)
            uiControls = this.UiControls;
            uiControls.BrikNameLabel.Enable = 'on';
            uiControls.BrikNameEditBox.Enable = 'on';
        end

        function DisableAfniFileOptionsPanel(this)
            uiControls = this.UiControls;
            uiControls.BrikNameLabel.Enable = 'off';
            uiControls.BrikNameEditBox.Enable = 'off';
        end

        function EnableRelaxivityControls(this)
            uiControls = this.UiControls;
            uiControls.LiverRelaxivityLabel.Enable = 'on';
            uiControls.LiverRelaxivityEditBox.Enable = 'on';
            uiControls.PlasmaRelaxivityLabel.Enable = 'on';
            uiControls.PlasmaRelaxivityEditBox.Enable = 'on';
            uiControls.BloodRelaxivityLabel.Enable = 'on';
            uiControls.BloodRelaxivityEditBox.Enable = 'on';
        end

        function DisableRelaxivityControls(this)
            uiControls = this.UiControls;
            uiControls.LiverRelaxivityLabel.Enable = 'off';
            uiControls.LiverRelaxivityEditBox.Enable = 'off';
            uiControls.PlasmaRelaxivityLabel.Enable = 'off';
            uiControls.PlasmaRelaxivityEditBox.Enable = 'off';
            uiControls.BloodRelaxivityLabel.Enable = 'off';
            uiControls.BloodRelaxivityEditBox.Enable = 'off';
        end

        function EnableDicomFileOptionsPanel(this)
            uiControls = this.UiControls;
            uiControls.FilenamePrefixLabel.Enable = 'on';
            uiControls.FilenamePrefixEditBox.Enable = 'on';
            uiControls.LeadingZerosCheckBox.Enable = 'on';
            uiControls.DigitPlacesLabel.Enable = 'on';
            uiControls.DigitPlacesEditBox.Enable = 'on';
            uiControls.FilenameExtensionLabel.Enable = 'on';
            uiControls.FilenameExtensionEditBox.Enable = 'on';
            uiControls.NumberOfSlicesLabel.Enable = 'on';
            uiControls.NumberOfSlicesEditBox.Enable = 'on';
        end

        function DisableDicomFileOptionsPanel(this)
            uiControls = this.UiControls;
            uiControls.FilenamePrefixLabel.Enable = 'off';
            uiControls.FilenamePrefixEditBox.Enable = 'off';
            uiControls.LeadingZerosCheckBox.Enable = 'off';
            uiControls.DigitPlacesLabel.Enable = 'off';
            uiControls.DigitPlacesEditBox.Enable = 'off';
            uiControls.FilenameExtensionLabel.Enable = 'off';
            uiControls.FilenameExtensionEditBox.Enable = 'off';
            uiControls.NumberOfSlicesLabel.Enable = 'off';
            uiControls.NumberOfSlicesEditBox.Enable = 'off';
        end

        function EnableFlipAngleEdit(this)
            uiControls = this.UiControls;
            uiControls.FlipAngleLabel.Enable = 'on';
            uiControls.FlipAngleEditBox.Enable = 'on';
        end

        function DisableFlipAngleEdit(this)
            uiControls = this.UiControls;
            uiControls.FlipAngleLabel.Enable = 'off';
            uiControls.FlipAngleEditBox.Enable = 'off';
        end

        function EnableEchoTimeEdit(this)
            uiControls = this.UiControls;
            uiControls.EchoTimeLabel.Enable = 'on';
            uiControls.EchoTimeEditBox.Enable = 'on';
        end

        function DisableEchoTimeEdit(this)
            uiControls = this.UiControls;
            uiControls.EchoTimeLabel.Enable = 'off';
            uiControls.EchoTimeEditBox.Enable = 'off';
        end

        function EnableRepetitionTimeEdit(this)
            uiControls = this.UiControls;
            uiControls.RepetitionTimeLabel.Enable = 'on';
            uiControls.RepetitionTimeEditBox.Enable = 'on';
        end

        function DisableRepetitionTimeEdit(this)
            uiControls = this.UiControls;
            uiControls.RepetitionTimeLabel.Enable = 'off';
            uiControls.RepetitionTimeEditBox.Enable = 'off';
        end

        function EnableOtherContrastAgentUiControls(this)
            uiControls = this.UiControls;
            model = this.Model;
            uiControls.OtherContrastAgentLabel.Enable = 'on';
            uiControls.OtherContrastAgentEditBox.Enable = 'on';

            % Can't use default relaxivity values for an unknown agent
            if(isfield(uiControls, 'UseDefaultRelaxivityCheckBox') && ...
                    isvalid(uiControls.UseDefaultRelaxivityCheckBox) && ...
                    uiControls.UseDefaultRelaxivityCheckBox.Value)
                uiControls.UseDefaultRelaxivityCheckBox.Value = 0;
            end
            model.UseDefaultRelaxivity = false;
            this.EnableRelaxivityControls();
        end

        function DisableOtherContrastAgentUiControls(this)
            uiControls = this.UiControls;
            uiControls.OtherContrastAgentLabel.Enable = 'off';
            uiControls.OtherContrastAgentEditBox.Enable = 'off';
        end

        function EnableOtherFieldStrengthUiControls(this)
            uiControls = this.UiControls;
            if(isvalid(uiControls.OtherFieldStrengthLabel))
                uiControls.OtherFieldStrengthLabel.Enable = 'on';
            end
            if(isvalid(uiControls.OtherFieldStrengthEditBox))
                uiControls.OtherFieldStrengthEditBox.Enable = 'on';
            end
        end

        function DisableOtherFieldStrengthUiControls(this)
            uiControls = this.UiControls;
            if(isvalid(uiControls.OtherFieldStrengthLabel))
                uiControls.OtherFieldStrengthLabel.Enable = 'off';
            end
            if(isvalid(uiControls.OtherFieldStrengthEditBox))
                uiControls.OtherFieldStrengthEditBox.Enable = 'off';
            end
        end
    end

    %% Static Methods
    methods (Static)
    end
end